# Generated by Django 4.1 on 2022-09-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnic193187', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ansver',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dnic193187.tests'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
